import { notFound } from 'next/navigation';
import Link from 'next/link';
import { getServerSession } from 'next-auth';
import { authOptions } from '@/lib/auth';
import { can } from '@/lib/rbac';
import { prisma } from '@/lib/prisma';
import { PageHeader } from '@/components/ui/PageHeader';
import { Card, CardBody } from '@/components/ui/Card';
import { Badge } from '@/components/ui/Badge';
import { GenerateSopButton } from '@/components/sop/GenerateSopButton';
import { SopStatusToggle } from '@/components/sop/SopStatusToggle';

export default async function SopDetailPage({ params }: { params: { id: string } }) {
  const session = await getServerSession(authOptions);
  if (!can(session?.user.role, 'interview.review')) notFound();

  const process = await prisma.process.findUnique({
    where: { id: params.id },
    include: { project: { include: { department: true } }, sop: { include: { generatedBy: true } } }
  });
  if (!process) notFound();

  return (
    <div>
      <PageHeader
        title={process.sop?.title || process.name || 'Untitled process'}
        subtitle={`${process.project.department.name} · ${process.project.name}`}
        actions={
          <>
            {process.status === 'NEEDS_REVIEW' ? <Badge tone="warning">Needs review</Badge> : null}
            {process.sop ? <Badge tone={process.sop.status === 'PUBLISHED' ? 'success' : 'neutral'}>{process.sop.status}</Badge> : null}
            <Link href="/sop-library" className="self-center text-sm text-brand-blue hover:underline">
              ← SOP Library
            </Link>
          </>
        }
      />

      {process.status === 'NEEDS_REVIEW' ? (
        <Card className="mb-4">
          <CardBody className="flex flex-wrap items-center justify-between gap-3">
            <p className="text-sm text-slate-600">
              Two or more employees described this process differently — resolve the conflicts before generating
              or updating its SOP.
            </p>
            <Link
              href={`/sop-library/${process.id}/reconcile`}
              className="whitespace-nowrap rounded-md bg-brand-blue px-3 py-1.5 text-sm font-semibold text-white hover:opacity-90"
            >
              Resolve conflicts
            </Link>
          </CardBody>
        </Card>
      ) : null}

      {!process.sop ? (
        <Card>
          <CardBody className="text-center">
            <p className="mb-3 text-sm text-slate-500">No SOP has been generated for this process yet.</p>
            <div className="flex justify-center">
              {process.status === 'NEEDS_REVIEW' ? null : <GenerateSopButton processId={process.id} />}
            </div>
          </CardBody>
        </Card>
      ) : (
        <div className="space-y-4">
          <Card>
            <CardBody className="flex flex-wrap items-center justify-between gap-3">
              <p className="text-xs text-slate-400">
                Generated by {process.sop.generatedBy.name} · {process.sop.generatedAt.toLocaleDateString()}
              </p>
              <div className="flex gap-2">
                <SopStatusToggle processId={process.id} status={process.sop.status as 'DRAFT' | 'PUBLISHED'} />
                {process.status === 'NEEDS_REVIEW' ? null : <GenerateSopButton processId={process.id} label="Regenerate" />}
              </div>
            </CardBody>
          </Card>

          <Card>
            <CardBody>
              <pre className="whitespace-pre-wrap font-sans text-sm leading-relaxed text-slate-700">{process.sop.contentMd}</pre>
            </CardBody>
          </Card>
        </div>
      )}
    </div>
  );
}
