import { notFound } from 'next/navigation';
import Link from 'next/link';
import { getServerSession } from 'next-auth';
import { authOptions } from '@/lib/auth';
import { can } from '@/lib/rbac';
import { prisma } from '@/lib/prisma';
import { PageHeader } from '@/components/ui/PageHeader';
import { Card, CardBody } from '@/components/ui/Card';
import { Badge } from '@/components/ui/Badge';
import { GenerateTrainingModuleButton } from '@/components/training/GenerateTrainingModuleButton';
import { TrainingModuleStatusToggle } from '@/components/training/TrainingModuleStatusToggle';

export default async function TrainingDetailPage({ params }: { params: { id: string } }) {
  const session = await getServerSession(authOptions);
  const canGenerate = can(session?.user.role, 'interview.review');
  if (!can(session?.user.role, 'interview.conduct') && !canGenerate) notFound();

  // params.id is the Process id, same convention as /sop-library/[id].
  const process = await prisma.process.findUnique({
    where: { id: params.id },
    include: {
      project: { include: { department: true } },
      sop: { include: { trainingModule: { include: { generatedBy: true } } } }
    }
  });
  if (!process || !process.sop) notFound();

  const trainingModule = process.sop.trainingModule;

  return (
    <div>
      <PageHeader
        title={trainingModule?.title || `Training: ${process.sop.title}`}
        subtitle={`${process.project.department.name} · ${process.project.name} · ${process.name || 'Untitled process'}`}
        actions={
          <>
            {trainingModule ? (
              <Badge tone={trainingModule.status === 'PUBLISHED' ? 'success' : 'neutral'}>{trainingModule.status}</Badge>
            ) : null}
            <Link href="/training" className="self-center text-sm text-brand-blue hover:underline">
              ← Training
            </Link>
          </>
        }
      />

      {!trainingModule ? (
        <Card>
          <CardBody className="text-center">
            <p className="mb-3 text-sm text-slate-500">No training module has been generated for this SOP yet.</p>
            {canGenerate ? (
              <div className="flex justify-center">
                <GenerateTrainingModuleButton processId={process.id} />
              </div>
            ) : null}
          </CardBody>
        </Card>
      ) : (
        <div className="space-y-4">
          {canGenerate ? (
            <Card>
              <CardBody className="flex flex-wrap items-center justify-between gap-3">
                <p className="text-xs text-slate-400">
                  Generated by {trainingModule.generatedBy.name} · {trainingModule.generatedAt.toLocaleDateString()}
                </p>
                <div className="flex gap-2">
                  <TrainingModuleStatusToggle
                    processId={process.id}
                    sopId={process.sop.id}
                    status={trainingModule.status as 'DRAFT' | 'PUBLISHED'}
                  />
                  <GenerateTrainingModuleButton processId={process.id} label="Regenerate" />
                </div>
              </CardBody>
            </Card>
          ) : null}

          <Card>
            <CardBody>
              <pre className="whitespace-pre-wrap font-sans text-sm leading-relaxed text-slate-700">{trainingModule.contentMd}</pre>
            </CardBody>
          </Card>
        </div>
      )}
    </div>
  );
}
