import { notFound } from 'next/navigation';
import Link from 'next/link';
import { getServerSession } from 'next-auth';
import { authOptions } from '@/lib/auth';
import { can } from '@/lib/rbac';
import { prisma } from '@/lib/prisma';
import { PageHeader } from '@/components/ui/PageHeader';
import { Card, CardBody } from '@/components/ui/Card';
import { Badge } from '@/components/ui/Badge';
import { GenerateAiProjectButton } from '@/components/ai-projects/GenerateAiProjectButton';
import { AiProjectStatusToggle } from '@/components/ai-projects/AiProjectStatusToggle';
import { PublishAgentButton } from '@/components/ai-projects/PublishAgentButton';

export default async function AiProjectDetailPage({ params }: { params: { id: string } }) {
  const session = await getServerSession(authOptions);
  if (!can(session?.user.role, 'interview.review')) notFound();

  // params.id is the AiOpportunity id — an AI project is a 1:1 synthesis of one opportunity,
  // same shape as SOP Library's process-keyed detail route.
  const opportunity = await prisma.aiOpportunity.findUnique({
    where: { id: params.id },
    include: {
      process: { include: { project: { include: { department: true } } } },
      aiProject: { include: { generatedBy: true, agent: true } }
    }
  });
  if (!opportunity) notFound();

  return (
    <div>
      <PageHeader
        title={opportunity.aiProject?.title || opportunity.title}
        subtitle={`${opportunity.process.project.department.name} · ${opportunity.process.project.name} · ${opportunity.process.name || 'Untitled process'}`}
        actions={
          <>
            {opportunity.aiProject ? (
              <Badge tone={opportunity.aiProject.status === 'PROPOSED' ? 'success' : 'neutral'}>{opportunity.aiProject.status}</Badge>
            ) : null}
            <Link href="/ai-projects" className="self-center text-sm text-brand-blue hover:underline">
              ← AI Projects
            </Link>
          </>
        }
      />

      {!opportunity.aiProject ? (
        <Card>
          <CardBody className="text-center">
            <p className="mb-3 text-sm text-slate-500">No AI project proposal has been generated for this opportunity yet.</p>
            <div className="flex justify-center">
              <GenerateAiProjectButton opportunityId={opportunity.id} />
            </div>
          </CardBody>
        </Card>
      ) : (
        <div className="space-y-4">
          <Card>
            <CardBody className="flex flex-wrap items-center justify-between gap-3">
              <p className="text-xs text-slate-400">
                Generated by {opportunity.aiProject.generatedBy.name} · {opportunity.aiProject.generatedAt.toLocaleDateString()}
              </p>
              <div className="flex gap-2">
                <AiProjectStatusToggle opportunityId={opportunity.id} status={opportunity.aiProject.status as 'DRAFT' | 'PROPOSED'} />
                <GenerateAiProjectButton opportunityId={opportunity.id} label="Regenerate" />
                {opportunity.aiProject.status === 'PROPOSED' ? (
                  opportunity.aiProject.agent ? (
                    <Link
                      href={`/agent-library/${opportunity.aiProject.agent.id}`}
                      className="inline-flex items-center rounded-lg border border-surface-border px-3 py-1.5 text-sm text-brand-blue hover:bg-brand-bluePale"
                    >
                      View in Agent Library
                    </Link>
                  ) : (
                    <PublishAgentButton opportunityId={opportunity.id} />
                  )
                ) : null}
                {opportunity.aiProject.status === 'PROPOSED' ? (
                  <Link
                    href={`/governance/${opportunity.id}`}
                    className="inline-flex items-center rounded-lg border border-surface-border px-3 py-1.5 text-sm text-brand-blue hover:bg-brand-bluePale"
                  >
                    Governance review
                  </Link>
                ) : null}
              </div>
            </CardBody>
          </Card>

          <Card>
            <CardBody>
              <pre className="whitespace-pre-wrap font-sans text-sm leading-relaxed text-slate-700">{opportunity.aiProject.contentMd}</pre>
            </CardBody>
          </Card>
        </div>
      )}
    </div>
  );
}
